import "./utils/smoothScroll.js";
import "./utils/home.js";
import "./utils/menu.js";
// import "./utils/scroll.js";
import "./utils/team.js";
import "./utils/feedback.js";
import "./utils/contacts.js";
import "./utils/breadcambs.js";
import "./utils/animate.js";
import "./utils/course.js";
import "./utils/education.js";
import "./utils/docs.js";
import "./utils/hull.js";